### ISSUE TITLE
About detail enhancement

### ISSUE THREAD

**Issue by musicrainie** [fqnchina/ImageSmoothing#3]
Hi, @fqnchina 
Let's say the input is "./images/detail_enhancement/detail_2_5.png", so the intermediate smooth image "detail_2_5-predict.png" can be inferred by the pre-trained model "./netfiles/model_smooth_detail-enhance_30.net", then how can I further get the final "detail_2_5-predict-detail.png"?

According to the paper, it can be obtained by the following process:
```
img_input = imread("./images/detail_enhancement/detail_2_5.png")
img_smooth = model(img_input, "./netfiles/model_smooth_detail-enhance_30.net")  # "detail_2_5-predict.png"

img_detail = img_input - img_smooth
img_detail_enhanced = enhance(img_detail)  # What's this exactly?

img_output = img_input + img_detail_enhanced  # "detail_2_5-predict-detail.png"
```

if I don't misunderstand, not so sure of myself.
Thank you in advance.

**Comment by fqnchina** [comment]
Hi,

I just upload some codes about the post processing of detail enhancement and stylization. After predicting the smooth images with our trained neural network, you should run post_detail_enhance.m to generate the final detail enhanced images. Note you can adjust some parameters in the matlab codes for different strength of exaggeration effects.

Sorry for the missing codes.

Thanks.

**Comment by musicrainie** [comment]
Now the final results of detail enhancement can be reproduced. Thanks for you prompt response.

**Comment by hypercost** [comment]
@fqnchina Hi, I cannot find where the function zeroone implements. 

https://github.com/fqnchina/ImageSmoothing/blob/master/util/tonemapLAB_simple.m#L26

**Comment by fqnchina** [comment]
Oh sorry. I just upload it.
